# Generated by Django 2.1.3 on 2019-05-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0002_emplo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emplo',
            table='Emplo',
        ),
    ]
